#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


METHOD_ORDER = [
    ("baseline", "Heuristic baseline"),
    ("multiclass", "Multiclass LightGBM"),
    ("reg_nearest", "Regression-quantization LightGBM"),
    ("ordinal_raw", "Ordinal LightGBM"),
    ("ordinal_tuned", "Ordinal + threshold tuning"),
    ("oracle", "Oracle upper bound"),
]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Export Group-A paper tables and oracle diagnostic from metrics JSON."
    )
    p.add_argument(
        "--metrics_json",
        type=str,
        default=r"F:\EngineeringWarehouse\NR\3D_noise_reduction\script\out_eval_groupA_paperA_oraclefix\metrics_groupA_full.json",
    )
    p.add_argument(
        "--out_dir",
        type=str,
        default="",
        help="Default to metrics_json parent when empty.",
    )
    return p.parse_args()


def f4(x: float) -> str:
    return f"{float(x):.4f}"


def f6(x: float) -> str:
    return f"{float(x):.6f}"


def load_payload(path: Path) -> Dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def build_table_a1_tex(decision_metrics: Dict[str, Dict]) -> str:
    lines: List[str] = []
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Table A1. Decision-level comparison under a unified protocol.}")
    lines.append(r"\label{tab:a1_decision}")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(r"\begin{tabular}{lcccccc}")
    lines.append(r"\toprule")
    lines.append(
        r"Method & Accuracy & Macro-F1 & MeanAbsClassError & TailRecall@24 & TailRecall@28 & TailRecall@31 \\"
    )
    lines.append(r"\midrule")
    for m, disp in METHOD_ORDER:
        met = decision_metrics[m]
        tr = met.get("tail_recall", {})
        lines.append(
            " & ".join(
                [
                    disp,
                    f4(met["accuracy"]),
                    f4(met["macro_f1"]),
                    f4(met["mean_abs_class_error"]),
                    f4(tr.get("24", float("nan"))),
                    f4(tr.get("28", float("nan"))),
                    f4(tr.get("31", float("nan"))),
                ]
            )
            + r" \\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines) + "\n"


def build_table_a2_tex(results: Dict, sigmas: List[int]) -> str:
    lines: List[str] = []
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering")
    lines.append(r"\caption{Table A2. Image-level comparison on DAVIS and Set8 (PSNR/SSIM).}")
    lines.append(r"\label{tab:a2_image}")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(r"\begin{tabular}{llccc}")
    lines.append(r"\toprule")
    lines.append(r"Dataset & Method & $\sigma=10$ & $\sigma=30$ & $\sigma=50$ \\")
    lines.append(r"\midrule")
    for ds in ["DAVIS", "Set8"]:
        first = True
        for m, disp in METHOD_ORDER:
            cells = []
            for s in sigmas:
                key = f"sigma_{s}"
                item = results[ds][key]["dataset_mean"][m]
                cells.append(f"{f4(item['psnr']['mean'])}/{f6(item['ssim']['mean'])}")
            if first:
                lines.append(
                    r"\multirow{"
                    + str(len(METHOD_ORDER))
                    + r"}{*}{"
                    + ds
                    + r"} & "
                    + disp
                    + " & "
                    + " & ".join(cells)
                    + r" \\"
                )
                first = False
            else:
                lines.append(" & " + disp + " & " + " & ".join(cells) + r" \\")
        lines.append(r"\midrule")
    if lines[-1] == r"\midrule":
        lines.pop()
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


def build_oracle_diagnostic_md(payload: Dict) -> str:
    dec = payload["decision_metrics"]["oracle"]
    acc = f4(dec["accuracy"])
    mf1 = f4(dec["macro_f1"])
    mae = f4(dec["mean_abs_class_error"])
    cfg = payload.get("config", {})
    mb = cfg.get("mb_size", 4)
    txt = []
    txt.append("# Oracle Branch Diagnostic")
    txt.append("")
    txt.append("## 1. Inference and Reconstruction Path")
    txt.append("")
    txt.append("- Oracle labels are generated by `oracle_lib.oracle_label_w`.")
    txt.append("- For each frame and each macroblock, the solver enumerates discrete weights in `w_set` and picks the minimum-loss weight.")
    txt.append("- In the fixed implementation, oracle reconstruction uses the same temporal blending form as other methods and uses oracle recursive reference.")
    txt.append("")
    txt.append("## 2. Oracle Objective Function")
    txt.append("")
    txt.append("- The objective is macroblock-level reconstruction error minimization, not direct frame-level PSNR/SSIM maximization.")
    txt.append("- Concretely, each candidate weight is applied with temporal IIR blending, then compared with ground truth using per-pixel absolute error aggregated at macroblock level.")
    txt.append(f"- Macroblock size in this run is `{mb}x{mb}`.")
    txt.append("")
    txt.append("## 3. Metric-Path Consistency Check")
    txt.append("")
    txt.append("- Decision-level oracle is evaluated against oracle labels generated under the same oracle branch path, so its decision metrics are identically optimal.")
    txt.append("- Image-level metrics are computed after frame reconstruction and therefore depend on objective mismatch and sequence dynamics.")
    txt.append("")
    txt.append("## 4. Interpretation of Decision-Level 1.0 vs Image-Level Metrics")
    txt.append("")
    txt.append("- Decision-level score 1.0 means the branch exactly predicts the labels used as supervision target.")
    txt.append("- This does not guarantee global optimum for PSNR/SSIM because the label objective is local macroblock MAE on a discrete set.")
    txt.append("- Frame-level PSNR/SSIM are nonlinear global metrics over all pixels and channels, and may diverge from local MAE optimum.")
    txt.append("- Therefore, oracle must be interpreted as an upper bound with respect to its verified local objective, not a universal upper bound for every image-level metric.")
    txt.append("")
    txt.append("## 5. Verified Result After Consistency Fix")
    txt.append("")
    sigmas = [10, 30, 50]
    for ds in ["DAVIS", "Set8"]:
        for s in sigmas:
            key = f"sigma_{s}"
            oracle_psnr = float(payload["results"][ds][key]["dataset_mean"]["oracle"]["psnr"]["mean"])
            others = []
            for m, _ in METHOD_ORDER:
                if m == "oracle":
                    continue
                others.append(float(payload["results"][ds][key]["dataset_mean"][m]["psnr"]["mean"]))
            best_non_oracle = max(others) if others else float("nan")
            delta = oracle_psnr - best_non_oracle
            txt.append(
                f"- {ds} sigma={s}: oracle PSNR={oracle_psnr:.4f}, "
                f"best non-oracle PSNR={best_non_oracle:.4f}, delta={delta:+.4f} dB."
            )
    txt.append("")
    txt.append("## 6. Current Oracle Decision Metrics")
    txt.append("")
    txt.append(f"- Accuracy: `{acc}`")
    txt.append(f"- Macro-F1: `{mf1}`")
    txt.append(f"- MeanAbsClassError: `{mae}`")
    txt.append("")
    return "\n".join(txt) + "\n"


def build_analysis_draft_md(payload: Dict) -> str:
    dm = payload["decision_metrics"]
    b = dm["baseline"]
    mc = dm["multiclass"]
    rg = dm["reg_nearest"]
    orr = dm["ordinal_raw"]
    ort = dm["ordinal_tuned"]
    txt = []
    txt.append("### Draft Analysis for Paper A Group")
    txt.append("")
    txt.append(
        "Under a unified protocol on DAVIS and Set8 with identical noise settings and frame budget, all learned methods significantly outperform the heuristic baseline in both decision-level and image-level metrics."
    )
    txt.append(
        f"Compared with the baseline, multiclass and regression-quantization already improve macro-level discrimination, with Macro-F1 increasing from {f4(b['macro_f1'])} to {f4(mc['macro_f1'])} and {f4(rg['macro_f1'])}, respectively."
    )
    txt.append(
        f"The ordinal formulation further improves class-structure awareness, lifting Macro-F1 to {f4(orr['macro_f1'])} while substantially improving tail-category recalls, especially for high-weight tail bins."
    )
    txt.append(
        f"Threshold tuning mainly benefits tail-sensitive categories rather than global accuracy, as reflected by the shift from ordinal raw to ordinal tuned in TailRecall@24/28/31 while overall accuracy changes from {f4(orr['accuracy'])} to {f4(ort['accuracy'])}."
    )
    txt.append(
        "The oracle branch should be interpreted separately according to the verified diagnostic result."
    )
    txt.append(
        "Its perfect decision-level score indicates consistency with its own supervision target, whereas image-level metrics reflect the gap between local macroblock MAE optimization and global frame-level perceptual or distortion criteria."
    )
    txt.append("")
    return "\n".join(txt) + "\n"


def main() -> None:
    args = parse_args()
    metrics_path = Path(args.metrics_json)
    if not metrics_path.is_file():
        raise SystemExit(f"metrics json not found: {metrics_path}")

    out_dir = Path(args.out_dir) if args.out_dir else metrics_path.parent
    out_dir.mkdir(parents=True, exist_ok=True)

    payload = load_payload(metrics_path)
    sigmas = [10, 30, 50]

    a1_tex = build_table_a1_tex(payload["decision_metrics"])
    a2_tex = build_table_a2_tex(payload["results"], sigmas)
    diag_md = build_oracle_diagnostic_md(payload)
    ana_md = build_analysis_draft_md(payload)

    (out_dir / "table_A1_decision.tex").write_text(a1_tex, encoding="utf-8")
    (out_dir / "table_A2_image.tex").write_text(a2_tex, encoding="utf-8")
    (out_dir / "oracle_diagnostic.md").write_text(diag_md, encoding="utf-8")
    (out_dir / "paperA_result_analysis_draft.md").write_text(ana_md, encoding="utf-8")

    print(f"[OUT] {out_dir / 'table_A1_decision.tex'}")
    print(f"[OUT] {out_dir / 'table_A2_image.tex'}")
    print(f"[OUT] {out_dir / 'oracle_diagnostic.md'}")
    print(f"[OUT] {out_dir / 'paperA_result_analysis_draft.md'}")


if __name__ == "__main__":
    main()
